# Proyecto de Sistemas de Big Data:D
**Autores:** Nicole Díaz y Enrique Ángel

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df_completo = pd.read_csv("csv/ventas.csv")
df_completo

,ID,ID_Pedido,ID_Factura,Supermercado,Ciudad,Tipo_cliente,Sexo,Linea_negocio,Precio_unitario,Cantidad,Total,IVA,Fecha,Pago
0,1,56904,56904-C1,Perfumes Olorosos,Vigo,Existente,Mujer,Belleza y perfumería,431.570,42,18125.90,3806.45,1973-09-25,Tarjeta crédito
1,2,56904,56904-C2,El Cercano,Pontevedra,Existente,Mujer,Supermercado,427.754,32,13688.10,2874.50,1973-09-25,Tarjeta crédito
2,3,56904,56904-C3,El Primero,Vigo,Existente,Mujer,Supermercado,125.120,55,6881.58,1445.13,1973-09-25,Tarjeta crédito
3,4,56904,56904-C4,Perfumes Olorosos,Vigo,Existente,Mujer,Belleza y perfumería,499.885,35,17496.00,3674.16,1973-09-25,Tarjeta crédito
4,5,56904,56904-C5,El Caro,Nigrán,Existente,Mujer,Cocinas,216.976,8,1735.81,364.52,1973-09-25,Tarjeta crédito
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,304,30066,30066-C3,Mercería Coso,A Coruña,Existente,Hombre,Otros,974.517,20,19490.30,4092.97,1998-02-04,Efectivo
304,305,30066,30066-C4,Mercería Coso,A Coruña,Existente,Hombre,Otros,131.573,39,5131.33,1077.58,1998-02-04,Efectivo
305,306,30066,30066-C5,Perfumes Olorosos,Vigo,Existente,Hombre,Belleza y perfumería,814.359,59,48047.20,10089.90,1998-02-04,Efectivo
306,307,30066,30066-C6,El Primero,Vigo,Existente,Hombre,Supermercado,867.107,90,78039.70,16388.30,1998-02-04,Efectivo
307,308,30066,30066-C7,Mercería Coso,A Coruña,Existente,Hombre,Otros,331.618,80,26529.40,5571.18,1998-02-04,Efectivo

DATAFRAME DE DIRECCIONES

In [2]:
direcciones_df = pd.read_csv("csv/DIRECCIONES.csv")
direcciones_df

,ID,ID_Pedido,dir_entrega,tipo_entrega,email
0,7,56904,"Gran vía 24 1C, Madrid",Correos,twana_ellwood@yahoo.com
1,8,84698,"Rúa Rosalía de castro 28 4B, Vigo",Domicilio,emery_aitken@mail.com
2,9,14325,"Avenida de Europa 2, Vigo",Correos,thomasina_stone@hotmail.com
3,10,68893,"c/Orense 25 2C, Madrid",Domicilio,justin_higgins@gmail.com
4,11,72994,"c/agua 25 3D, Sevilla",Punto de recogida,liliana_wilde@outlook.com
5,12,82407,"c/San Lorenzo 12, Málaga",Domicilio,bo_finnegan@hotmail.com
6,13,74285,"Avinguda de Manuel Azaña 4, Barcelona",Domicilio,mayme_driscoll@yandex.com
7,14,5364,"Avenida de Casablanca 45, Madrid",Correos,jenifer_reid@zohomail.com
8,15,80407,"Calle de Canarias 1 2B, Madrid",Punto de recogida,julie_macgregor@gmail.com
9,16,18447,"c/Esla 34, León",Domicilio,yvonne_povey@mail.com
10,17,76092,"Cami Assagador del Morro 12, Valencia",Domicilio,magdalene_mcrae@yandex.com
11,18,60659,"C/Burriana 12 3C, Oviedo",Domicilio,minta_hodge@yandex.com
12,19,44964,"c/González del Villar 12, A Coruña",Domicilio,samara_bright@yandex.com
13,20,87871,"Rúa Lepanto 4 3A, Vigo",Domicilio,coy_rice@gmail.com
14,21,86276,"Rúa Amado Carballo 10 1A, Ourense",Domicilio,cleotilde_hargreaves@aol.com
15,22,98183,"Avenida de Cataluña 22, Zaragoza",Punto de recogida,brendan_weir@yandex.com
16,23,71938,"Avenida de los Pilares 30, Cáceres",Correos,danelle_sanderson@yahoo.com
17,24,96811,"c/Blanco Coris 23 1C, Málaga",Domicilio,NaN
18,25,12573,"Bajada antequeruela 5, Toledo",Domicilio,claretha_mcgill@yandex.com
19,26,31349,"c/Daoíz y Velarde 5 2A, León",Punto de recogida,len_hartley@yahoo.com
20,27,18447,"c/Esla 34, León",Domicilio,yvonne_povey@mail.com
21,28,23052,"Rúa Rosalía de castro 28 4B, Vigo",Domicilio,tona_hobbs@yahoo.com
22,29,28324,"Gran vía 24 1C, Madrid",Domicilio,tanner_russell@protonmail.com
23,30,78031,"Avenida da Concordia 12, A Coruña",Domicilio,sid_wilks@protonmail.com
24,31,38805,"c/Nuevas Profesiones 5 5D, Sevilla",Domicilio,sarai_kendall@gmail.com
25,32,55280,"Avinguda de Manuel Azaña 4, Barcelona",Domicilio,tenisha_ward@yahoo.com
26,33,78844,"c/González Besada 12 3A, Oviedo",Domicilio,margit_appleton@aol.com
27,34,28966,"c/San Lorenzo 12, Málaga",Domicilio,carl_levy@hotmail.com
28,35,44903,"Rúa Petanca 5, Ourense",Domicilio,alvaro_greig@yandex.com
29,36,34175,"Carrer de Santaló 3 1B, Barcelona",Punto de recogida,roger_raymond@outlook.com
30,37,77345,"Avenida de Casablanca 45, Madrid",Domicilio,samantha_haines@zohomail.com
31,38,3800,"Calle de Canarias 1 2B, Madrid",Correos,dee_phillips@protonmail.com
32,39,71084,"c/del Lirio 3 1A, Ciudad Real",Domicilio,alfredia_peterson@hotmail.com
33,40,22315,"Avenida de Carlos 2 1A, Toledo",Domicilio,bao_allan@zohomail.com
34,41,33380,"Calle de Santa Inés 5, Madrid",Domicilio,eura_mcintyre@zohomail.com
35,42,22397,"Cami Assagador del Morro 12, Valencia",Domicilio,antone_george@protonmail.com
36,43,68207,"Avenida Ruta de la Plata 5 1A, Cáceres",Domicilio,grace_cohen@protonmail.com
37,44,29986,"Rúa Rosalía de castro 28 4B, Vigo",Domicilio,jeanine_barnard@mail.com
38,45,17669,"c/González del Villar 12, A Coruña",Domicilio,norah_clayton@protonmail.com
39,46,58904,"c/La nave, Zaragoza",Correos,gayle_khan@mail.com
40,47,37331,"Gran vía 24 1C, Madrid",Domicilio,peter_arnold@yandex.com
41,48,6777,"Carrer de Manuel de Falla 24, Barcelona",Domicilio,sunny_mullins@yahoo.com
42,49,10018,"Rúa Lepanto 4 3A, Vigo",Domicilio,clelia_sanchez@gmail.com
43,50,31627,"Rúa Amado Carballo 10 1A, Ourense",Punto de recogida,arielle_duffy@aol.com
44,51,46547,"Rúa do Picouto 12 2A, Ourense",Punto de recogida,viki_charles@gmail.com
45,52,95073,"Avenida de Cataluña 22, Zaragoza",Domicilio,dinorah_sadler@yahoo.com
46,53,40579,"Avenida de Francia 34, Valencia",Punto de recogida,archie_o brien@aol.com
47,54,28239,"Avenida de los Pilares 30, Cáceres",Domicilio,sebastian_curry@hotmail.com
48,55,5220,"c/Blanco Coris 23 1C, Málaga",Correos,virginia_cooke@yahoo.com
49,56,27943,"Bajada antequeruela 5, Toledo",Correos,shaquana_miles@mail.com
50,57,28497,"c/Esla 34, León",Domicilio,evia_redman@yahoo.com
51,58,51480,"Avenida da Concordia 12, A Coruña",Domicilio,beverley_brookes@aol.com
52,59,72208,"Calle del Lucero 12 6A, Madrid",Domicilio,NaN
53,60,56277,"C/Burriana 12 3C, Oviedo",Punto de recogida,noella_drew@protonmail.com
54,61,71233,"c/del Lirio 3 1A, Ciudad Real",Punto de recogida,adella_steadman@outlook.com
55,62,26364,"Calle de Eugenia de Montijo 3, Madrid",Domicilio,beth_horner@aol.com
56,63,11542,"c/Padre Barranco 5 1A, Valencia",Domicilio,jacalyn_mccarthy@protonmail.com
57,64,68207,"Avenida Ruta de la Plata 5 1A, Cáceres",Domicilio,grace_cohen@protonmail.com
58,65,30066,"Calle Ugalde 10 4C, Bilbao",Domicilio,cris_watt@hotmail.com
59,66,18447,"c/Esla 34, León",Domicilio,yvonne_povey@mail.com

----

AÑADIMOS LA NUEVA COLUMNA TIPO DE ENTREGA
-----------

In [3]:
# merge funcion con el on: donde va las columnas comunes, how el tipo de union: 
df_completo = df_completo.merge(direcciones_df[['ID_Pedido', 'tipo_entrega']], on='ID_Pedido', how='left')
df_completo

,ID,ID_Pedido,ID_Factura,Supermercado,Ciudad,Tipo_cliente,Sexo,Linea_negocio,Precio_unitario,Cantidad,Total,IVA,Fecha,Pago,tipo_entrega
0,1,56904,56904-C1,Perfumes Olorosos,Vigo,Existente,Mujer,Belleza y perfumería,431.570,42,18125.90,3806.45,1973-09-25,Tarjeta crédito,Correos
1,2,56904,56904-C2,El Cercano,Pontevedra,Existente,Mujer,Supermercado,427.754,32,13688.10,2874.50,1973-09-25,Tarjeta crédito,Correos
2,3,56904,56904-C3,El Primero,Vigo,Existente,Mujer,Supermercado,125.120,55,6881.58,1445.13,1973-09-25,Tarjeta crédito,Correos
3,4,56904,56904-C4,Perfumes Olorosos,Vigo,Existente,Mujer,Belleza y perfumería,499.885,35,17496.00,3674.16,1973-09-25,Tarjeta crédito,Correos
4,5,56904,56904-C5,El Caro,Nigrán,Existente,Mujer,Cocinas,216.976,8,1735.81,364.52,1973-09-25,Tarjeta crédito,Correos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,304,30066,30066-C3,Mercería Coso,A Coruña,Existente,Hombre,Otros,974.517,20,19490.30,4092.97,1998-02-04,Efectivo,Domicilio
317,305,30066,30066-C4,Mercería Coso,A Coruña,Existente,Hombre,Otros,131.573,39,5131.33,1077.58,1998-02-04,Efectivo,Domicilio
318,306,30066,30066-C5,Perfumes Olorosos,Vigo,Existente,Hombre,Belleza y perfumería,814.359,59,48047.20,10089.90,1998-02-04,Efectivo,Domicilio
319,307,30066,30066-C6,El Primero,Vigo,Existente,Hombre,Supermercado,867.107,90,78039.70,16388.30,1998-02-04,Efectivo,Domicilio
320,308,30066,30066-C7,Mercería Coso,A Coruña,Existente,Hombre,Otros,331.618,80,26529.40,5571.18,1998-02-04,Efectivo,Domicilio

AÑADIMOS LA COLUMNA DE NOMBRE DE USUARIOS 
-----------

In [4]:
df_completo = df_completo.merge(
    direcciones_df[['ID_Pedido', 'email']],
    on='ID_Pedido',
    how='left'
)
df_completo['nombre_usuario'] = df_completo['email'].str.split('@', expand=True)[0]
df_completo['nombre_usuario'] = df_completo['nombre_usuario'].fillna('DESCONOCIDO')
df_completo

,ID,ID_Pedido,ID_Factura,Supermercado,Ciudad,Tipo_cliente,Sexo,Linea_negocio,Precio_unitario,Cantidad,Total,IVA,Fecha,Pago,tipo_entrega,email,nombre_usuario
0,1,56904,56904-C1,Perfumes Olorosos,Vigo,Existente,Mujer,Belleza y perfumería,431.570,42,18125.90,3806.45,1973-09-25,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
1,2,56904,56904-C2,El Cercano,Pontevedra,Existente,Mujer,Supermercado,427.754,32,13688.10,2874.50,1973-09-25,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
2,3,56904,56904-C3,El Primero,Vigo,Existente,Mujer,Supermercado,125.120,55,6881.58,1445.13,1973-09-25,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
3,4,56904,56904-C4,Perfumes Olorosos,Vigo,Existente,Mujer,Belleza y perfumería,499.885,35,17496.00,3674.16,1973-09-25,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
4,5,56904,56904-C5,El Caro,Nigrán,Existente,Mujer,Cocinas,216.976,8,1735.81,364.52,1973-09-25,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,304,30066,30066-C3,Mercería Coso,A Coruña,Existente,Hombre,Otros,974.517,20,19490.30,4092.97,1998-02-04,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
351,305,30066,30066-C4,Mercería Coso,A Coruña,Existente,Hombre,Otros,131.573,39,5131.33,1077.58,1998-02-04,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
352,306,30066,30066-C5,Perfumes Olorosos,Vigo,Existente,Hombre,Belleza y perfumería,814.359,59,48047.20,10089.90,1998-02-04,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
353,307,30066,30066-C6,El Primero,Vigo,Existente,Hombre,Supermercado,867.107,90,78039.70,16388.30,1998-02-04,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
354,308,30066,30066-C7,Mercería Coso,A Coruña,Existente,Hombre,Otros,331.618,80,26529.40,5571.18,1998-02-04,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt

--------------------------------

Este dataframe df_completo solo debe tener como índice el ID Factura.
-------

In [5]:

df_completo.set_index(['ID_Factura'], inplace=True)
df_completo.index

Index(['56904-C1', '56904-C2', '56904-C3', '56904-C4', '56904-C5', '56904-C6',
       '84698-C1', '14325-C1', '14325-C2', '14325-C3',
       ...
       '11542-C8', '11542-C9', '11542-C10', '30066-C1', '30066-C2', '30066-C3',
       '30066-C4', '30066-C5', '30066-C6', '30066-C7'],
      dtype='object', name='ID_Factura', length=355)

-------------

No debe figurar el Comercio, ya que no le aporta información. Tampoco debe figurar otra información que sea redundante. Ni la fecha de compra
-----------

In [6]:
df_completo.drop(columns=['Supermercado', 'Fecha'], inplace=True)
df_completo

,ID,ID_Pedido,Ciudad,Tipo_cliente,Sexo,Linea_negocio,Precio_unitario,Cantidad,Total,IVA,Pago,tipo_entrega,email,nombre_usuario
ID_Factura,,,,,,,,,,,,,,
56904-C1,1,56904,Vigo,Existente,Mujer,Belleza y perfumería,431.570,42,18125.90,3806.45,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
56904-C2,2,56904,Pontevedra,Existente,Mujer,Supermercado,427.754,32,13688.10,2874.50,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
56904-C3,3,56904,Vigo,Existente,Mujer,Supermercado,125.120,55,6881.58,1445.13,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
56904-C4,4,56904,Vigo,Existente,Mujer,Belleza y perfumería,499.885,35,17496.00,3674.16,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
56904-C5,5,56904,Nigrán,Existente,Mujer,Cocinas,216.976,8,1735.81,364.52,Tarjeta crédito,Correos,twana_ellwood@yahoo.com,twana_ellwood
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30066-C3,304,30066,A Coruña,Existente,Hombre,Otros,974.517,20,19490.30,4092.97,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
30066-C4,305,30066,A Coruña,Existente,Hombre,Otros,131.573,39,5131.33,1077.58,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
30066-C5,306,30066,Vigo,Existente,Hombre,Belleza y perfumería,814.359,59,48047.20,10089.90,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
30066-C6,307,30066,Vigo,Existente,Hombre,Supermercado,867.107,90,78039.70,16388.30,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt
30066-C7,308,30066,A Coruña,Existente,Hombre,Otros,331.618,80,26529.40,5571.18,Efectivo,Domicilio,cris_watt@hotmail.com,cris_watt

--------

Se deben preprocesar los datos para dotar a la información de calidad. Incluye tratamiento de nulos o duplicados, por ejemplo.